# ~/.config/kitty/current-theme.conf
# Oxocarbon (Refined)

background              #161616
foreground              #f2f4f8

selection_background    #2a2a2a
selection_foreground    #ffffff

cursor                  #78a9ff
cursor_text_color       #161616

url_color               #33b1ff

active_border_color     #78a9ff
inactive_border_color   #262626
bell_border_color       #ee5396

active_tab_background   #262626
active_tab_foreground   #ffffff
inactive_tab_background #161616
inactive_tab_foreground #6f6f6f

mark1_background        #be95ff
mark1_foreground        #161616

# Normal Colors
color0  #161616
color1  #ee5396
color2  #42be65
color3  #08bdba
color4  #78a9ff
color5  #be95ff
color6  #3ddbd9
color7  #dde1e6

# Bright Colors
color8  #525252
color9  #ff7eb6
color10 #6fdc8c
color11 #3ddbd9
color12 #82cfff
color13 #d4bbff
color14 #82f4f4
color15 #ffffff
